Repository demisto/demisto-sdk, pull requests merged in 2024-03, with the labels that each got.

#3820 README Contribution Generation and Update
  .changelog/3820.yml
  TestSuite/repo.py
  demisto_sdk/commands/common/constants.py
  demisto_sdk/commands/common/git_util.py
  demisto_sdk/commands/common/tools.py
  demisto_sdk/commands/generate_docs/common.py
  demisto_sdk/commands/generate_docs/generate_integration_doc.py
  demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_commands/AHA.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_commands/AHA_added_cmd.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_commands/README.md
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_conf_cmd_modified_cmd/README.md
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_conf_cmd_modified_cmd/SplunkPy.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_conf_cmd_modified_cmd/SplunkPy_update.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_configuration/AHA.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_configuration/AHA_added_conf.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_added_configuration/README.md
  demisto_sdk/commands/generate_docs/tests/test_files/test_update_commands_section/AHA.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_update_commands_section/AHA_modified_cmds.yml
  demisto_sdk/commands/generate_docs/tests/test_files/test_update_commands_section/README.md
  demisto_sdk/commands/init/contribution_converter.py
  demisto_sdk/commands/init/tests/contribution_converter_test.py
  demisto_sdk/commands/init/tests/test_files/common/README.md
  demisto_sdk/commands/init/tests/test_files/common/integration.py
  demisto_sdk/commands/init/tests/test_files/common/integration.yml
  demisto_sdk/commands/init/tests/test_files/test_convert_contribution_dir_to_pack_contents/contribution_indicatorfield_and_incidentfield.zip
  demisto_sdk/commands/init/tests/test_files/test_convert_contribution_dir_to_pack_contents/contribution_indicatorfield_only.zip
  demisto_sdk/commands/init/tests/test_files/test_fixup_detected_content_items_automation/test_fixup_detected_content_items_automation.zip
  demisto_sdk/commands/init/tests/test_files/test_fixup_detected_content_items_integration/contentpack-abuse_Contribution_Pack.zip
  demisto_sdk/commands/init/tests/test_files/test_fixup_detected_content_items_servicenow/uploads_edb61840-4575-406b-93ed-c20d30200c70_pack.zip
  demisto_sdk/commands/init/tests/test_files/test_process_existing_pack_existing_integration_readme/existing_pack_add_integration_cmd.json
  demisto_sdk/commands/init/tests/test_files/test_process_existing_pack_existing_integration_readme/existing_pack_add_integration_cmd.zip
  demisto_sdk/commands/init/tests/test_files/test_process_existing_pack_modified_cmd_conf_added_cmd_up_to_date/README.md
  demisto_sdk/commands/init/tests/test_files/test_process_existing_pack_modified_cmd_conf_added_cmd_up_to_date/SplunkPy.yml
  demisto_sdk/commands/init/tests/test_files/test_process_existing_pack_modified_cmd_conf_added_cmd_up_to_date/content_mapping.json
  demisto_sdk/commands/init/tests/test_files/test_process_existing_pack_modified_cmd_conf_added_cmd_up_to_date/pack.zip
  demisto_sdk/commands/init/tests/test_files/test_process_existing_pack_new_integration_readme/existing_pack_new_integration.zip
  demisto_sdk/commands/init/tests/test_files/test_process_new_pack/new_pack_new_integration.zip
  demisto_sdk/commands/init/tests/test_files/test_rearranging_before_conversion_indicator_and_incident_fields/contribution_indicatorfield_and_incidentfield.zip
  demisto_sdk/commands/init/tests/test_files/test_rearranging_before_conversion_indicator_fields/contribution_indicatorfield_only.zip
  demisto_sdk/commands/integration_diff/integration_diff_detector.py
  demisto_sdk/commands/integration_diff/tests/HelloWorld_new.yml
  demisto_sdk/commands/integration_diff/tests/HelloWorld_old.yml
  demisto_sdk/commands/integration_diff/tests/integration_diff_test.py
Labels: bug, enhancement

#4082 [CI] - release SDK to pypi github action
  .github/workflows/release-to-pypi.yml
Labels: release-sdk-to-pypi

#4110 fix upload readme
  demisto_sdk/commands/upload/README.md
Labels: docs-approved

#4140 [README] Added `Docker Usage`
  README.md
  demisto_sdk/commands/generate_docs/README.md
  demisto_sdk/commands/lint/lint_manager.py
Labels: docs-approved

#4114 Officialize validate refactor
  .changelog/4114.yml
  .github/workflows/on-push.yml
  demisto_sdk/__main__.py
  demisto_sdk/commands/common/schemas/integration.yml
  demisto_sdk/commands/common/tests/pack_unique_files_test.py
  demisto_sdk/commands/common/tools.py
  demisto_sdk/commands/validate/README.md
  demisto_sdk/commands/validate/config_reader.py
  demisto_sdk/commands/validate/default_config.toml
  demisto_sdk/commands/validate/initializer.py
  demisto_sdk/commands/validate/old_validate_readme.md
  demisto_sdk/commands/validate/sdk_validation_config.toml
  demisto_sdk/commands/validate/tests/validators_test.py
  demisto_sdk/commands/validate/validate_manager.py
  demisto_sdk/commands/validate/validation_results.py
  demisto_sdk/commands/validate/validators/base_validator.py
  demisto_sdk/scripts/add_marketplace_to_schemas.py
  demisto_sdk/tests/conf_file_test.py
  demisto_sdk/tests/integration_tests/format_integration_test.py
  demisto_sdk/tests/integration_tests/validate_integration_test.py
  demisto_sdk/tests/workflow_test.py
Labels: docs-approved
